### ISSUE TITLE
Semantic networks have no edge weights

### ISSUE THREAD

**Issue by sbinn** [vosonlab/vosonSML#12]
When creating semantic networks, it seems that edge weights are all "NA". 

![Edge Weights Semantic](https://user-images.githubusercontent.com/48778310/54734742-7c860100-4bed-11e9-9c1a-b6cec71d544c.png)

Tested with Twitter data in Versions 0.26.2 and 0.27.0. I'm not sure since which version this appears, but in some previous version edge weights had actual values.

**Comment by mishoryu** [comment]
Hi sbinn, thank you for submitting this issue. I suspect this is the result of our code inadvertently passing one or more NA's to the sum operation that produces the weight values. Will investigate further.

**Comment by mishoryu** [comment]
This issue has now been fixed in #13.
