### ISSUE TITLE
Error in collecting YouTube video comments

### ISSUE THREAD

**Issue by ktanaka086** [vosonlab/vosonSML#20]
Hi!

I tried to collect some YouTube comment data (e.g., https://www.youtube.com/watch?v=ATYK2svJ6eM). However, I got an error like:
`Error in Collect.youtube(., videoIDs = myYoutubeVideoIds, maxComments = 100,  : No comments could be collected from the given video Ids: ATYK2svJ6eM`

I also asked my colleague to try to do the same thing using a different YouTube video and replicated the same error.

And the error seems similar to this one: https://github.com/vosonlab/SocialMediaLab/issues/14

I'm using Windows 10, R 3.5.1, and vosonSML 0.27.2.

Thanks for your help in advance!

**Comment by mishoryu** [comment]
Hi there,

Thanks for the message. I've tested with the youtube video you provided and was able to collect comments. If you are using the same API key and cannot collect comments for any videos it is likely a problem with the API key or rate-limiting.

If you are sure your API key is correct, you can test it with the following code snippet and gather some more information about the problem:
```R
library(httr)
youtube_key <- "xxxxxxxx"
req <- httr::GET("https://www.googleapis.com/youtube/v3/search", 
                            query = list(part = "snippet",
                            q = "programming",
                            maxResults = 25,
                            key = youtube_key))

httr::content(req)

# check the values of $error$code and $error$message
```
In the last few months I've encountered a problem with Google where certain peoples API keys that were previously working are no longer working even though everything looks correct on the Google API Developers Console site. Even if they generate new keys these will not work either.

The snippit produces an error message as follows in this case:
```R
$error$code
[1] 403
$error$message
[1] "Access Not Configured. 
YouTube Data API has not been used in project XXXXXXXXXXXXX before or it is disabled. 
Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=XXXXXXXXXX then retry.
If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
```
If you are encountering the same problem, I have found a possible solution which is to create a new Google Project and then create a new API key under that new project on the API Developers Console. The new key should work as expected.

**Comment by ktanaka086** [comment]
Thank you so much for your help! The workaround solution actually worked - I created a new project and then generated a new API key.
