### ISSUE TITLE
Error creating an actorNetwork

### ISSUE THREAD

**Issue by MonchoCastro** [vosonlab/vosonSML#39]
When I try to network with the actors in a video, people who comment and their responses, I get the following error:

Generating youtube actor network...**Error: `x` must be a vector, not a `tbl_df/tbl/data.frame/datasource/youtube` object.**

I review the code and write it in different ways but for the moment i am getting this. How can i fix it? The code is the following one:

```
library(vosonSML)
library(devtools)

apikey <- "xxxxxxx"
key <- Authenticate("youtube", 
                    apiKey=apikey)

video = c("2GRs1HKaLnA)  #Example

actorNetwork <- Authenticate("youtube", apiKey = apikey) %>%
                Collect(videoIDs = video) %>%
                Create("actor", writeToFile = TRUE)
```

As I said I tried different ways:

```
youtubeData <- youtubeAuth %>%
               Collect(videoIDs = video, maxComments = 500, writeToFile = TRUE)

#Note that if you read the YouTube dataframe from disk, you will need to modify the class values for the object, before you can use it with vosonSML:

youtubeData <- readRDS("/path/to/data/data.rds")
class(youtubeData) <- append(class(youtubeData), c("datasource", "youtube"))

actorNetwork <- youtubeData %>% Create("actor") %>% AddText(youtubeData)
```

Anyone could help me please??

 thank you very much!

**Comment by mishoryu** [comment]
Hi,

Thank you for your message. This error is caused by recent breaking changes in the `dplyr` package version 1.0 that now requires a different order of custom classes attached to dataframes. We've fixed this in the latest development version of `vosonSML` that you can install from github using `devtools` or `remotes`.

```r
devtools::install_github("vosonlab/vosonSML")
```

Apologies the example from the vignette probably needs an update as well, I don't believe any modification to classes is still required after the `readRDS`. So after updating you should be able to simply enter:

```r
youtubeData <- readRDS("/path/to/data/data.rds")
actorNetwork <- youtubeData %>% Create("actor") %>% AddText(youtubeData)
```

Please let me know if you have any further issues.

**Comment by MonchoCastro** [comment]
> Hi,
> 
> Thank you for your message. This error is caused by recent breaking changes in the `dplyr` package version 1.0 that now requires a different order of custom classes attached to dataframes. We've fixed this in the latest development version of `vosonSML` that you can install from github using `devtools` or `remotes`.
> 
> ```r
> devtools::install_github("vosonlab/vosonSML")
> ```
> 
> Apologies the example from the vignette probably needs an update as well. It's probably easier to use `ImportData` rather than `readRDS`. So after updating you should be able to simply enter:
> 
> ```r
> youtubeData <- ImportData("/path/to/data/data.rds", "youtube")
> actorNetwork <- youtubeData %>% Create("actor") %>% AddText(youtubeData)
> ```
> 
> Please let me know if you have any further issues.

Thank you very

**Comment by MonchoCastro** [comment]
> Hi,
> 
> Thank you for your message. This error is caused by recent breaking changes in the `dplyr` package version 1.0 that now requires a different order of custom classes attached to dataframes. We've fixed this in the latest development version of `vosonSML` that you can install from github using `devtools` or `remotes`.
> 
> ```r
> devtools::install_github("vosonlab/vosonSML")
> ```
> 
> Apologies the example from the vignette probably needs an update as well. It's probably easier to use `ImportData` rather than `readRDS`. So after updating you should be able to simply enter:
> 
> ```r
> youtubeData <- ImportData("/path/to/data/data.rds", "youtube")
> actorNetwork <- youtubeData %>% Create("actor") %>% AddText(youtubeData)
> ```
> 
> Please let me know if you have any further issues.

Thank you very much! Now it works perfectly!
