### ISSUE TITLE
Error in the creation of the activity network graph 

### ISSUE THREAD

**Issue by ramattos7** [vosonlab/vosonSML#44]
When I load a .rds file and try to run an activity network graph, the following error message appears :

> 
> activityNetwork <- twitterData %>% 
>   Create("activity") %>%
>   Graph(writeToFile = TRUE) %>%
>   summary()

```
Creating igraph network graph...Generating twitter activity network...

-------------------------
collected tweets | 370562
quote tweets     | 39868
reply tweets     | 182792
tweets           | 147902
nodes from data  | 79492
nodes            | 450054
edges            | 222660
-------------------------
Done.
Error in igraph::graph_from_data_frame(d = net$edges, directed = directed,  : 
  Duplicate vertex names 

```

**Comment by bryn-g** [comment]
Hi @ramattos7, thank you for posting this issue. I think this may be a bug in the construction of the activity network in which duplicate nodes (tweets) are not being removed from the nodes data frame properly. Could you please let me know what version of the `vosonSML` package you are using with `packageVersion("vosonSML")`?

In the meantime you should be able to resolve this problem by removing the duplicate nodes as follows:
```R
library(dplyr)

activityNetwork <- twitterData %>% Create("activity")

activityNetwork$nodes <- activityNetwork$nodes %>%
  distinct(status_id, .keep_all = TRUE)

activityNetwork %>% Graph(writeToFile = TRUE)
```

**Comment by ramattos7** [comment]
Hi @bryn-g , thanks very much for your help. I solved the problem. 
The version is` ‘0.29.13’`
