### ISSUE TITLE
Broken documentation link & import Rtweet

### ISSUE THREAD

**Issue by lfagliano** [vosonlab/vosonSML#47]
Hey VosonLab! 

First, great tool, I have been exploring the functionalities and I am eager to use it in my project. I just wanted to let you know that the following link (https://vosonlab.github.io/posts/2021-02-11_twitter_vsml_from_rtweet/) is broken in the documentation page... coincidentally I was trying to find how to load my Rtweet dataset directly, without having to run collect through the package. Is that possible?

Also, is it possible to connect to other endpoints of the twitter API, like the getTimeline ?

Best, 
Lucas

**Comment by bryn-g** [comment]
Hi Lucas,

Apologies for the broken link, some of our article titles changed recently. I'll fix that up but in the meantime the article you referenced can be found on our [code blog](https://vosonlab.github.io/) under [Creating Twitter Networks with vosonSML using rtweet Data](https://vosonlab.github.io/posts/2021-02-11_twitter_vosonsml_from_rtweet/).

We use the `rtweet` package to perform our standard twitter searches and collection so it is usually no problem using data collected through various `rtweet` operations. It can simply be imported using the  `vosonSML` [ImportData](https://vosonlab.github.io/vosonSML/reference/ImportData.html) function as in the following example using the `rtweet` timeline collection:

```r
library(magrittr)
library(rtweet)
library(vosonSML)

token <- readRDS("~/.rtweet_oauth1a") # set NULL to use rtweet app

tweets <- get_timeline(c("vosonlab"), n = 100, token = token)

data <- tweets %>% ImportData("twitter") # import data

actor_network <- data %>%
  Create("actor") %>%                    # create actor network from tweets
  AddText(data) %>%                      # add tweet text as edge attributes
  AddUserData(data, lookupUsers = FALSE) # add users profile metadata as node attributes
```

Hope that helps and thanks for the feedback!

**Comment by lfagliano** [comment]
Hi Bryn, 

Thanks for your response, and for sharing the link! 

However, the snippet you shared did not work when I replicated it. For some reason, it gives me an error of file format not supported. 

```
library(tidyverse)
library(rtweet)
library(vosonSML)

pm_try<- get_timeline(c("vosonlab"),n=100)  
try_voson <- pm_try %>% ImportData("twitter")

Error: File format not supported. please choose from: csv, rds.
In addition: Warning message:
In if (!type %in% supported_types) { :
  the condition has length > 1 and only the first element will be used

```

As a workaround, I wrote the Rtweet df into csv (actually I had no clue that Rtweet came with its own function for that and your blog made me aware of that, thanks!), and then importData on the csv file with socialmedia= "twitter". That appears to have worked. 

Best, 
L

**Comment by bryn-g** [comment]
Hi Lucas,

Apologies again for that! You are probably using the CRAN version `0.29.13` which has an earlier version of `ImportData` that does not yet support input of `data.frame` type. I would recommend trying the github version of the `vosonSML` package `0.30.5` or saving your collected timeline data as a `.rds` file and importing that as per your workaround. The `.csv` import works and is probably fine but my personal preference would be to avoid text based data export and import whenever possible in case it introduces text encoding issues.

```r
# install dev version of vosonSML from github
library(remotes)
install_github("vosonlab/vosonSML")

library(vosonSML)
pm_try<- get_timeline(c("vosonlab"),n=100)  
try_voson <- pm_try %>% ImportData("twitter")

# or workaround with rds file for CRAN version
pm_try<- get_timeline(c("vosonlab"),n=100) 
saveRDS(pm_try, "vosonlab_timeline_n100.rds")

try_voson <- ImportData("vosonlab_timeline_n100.rds", "twitter")
actor_network  <- try_voson %>% Create("actor")

# > actor_network$nodes %>% slice_head()
# # A tibble: 1 x 2
#   user_id            screen_name
#   <chr>              <chr>      
# 1 761799570426765312 vosonlab

# > actor_network$edges %>% slice_head()
# # A tibble: 1 x 5
#   from               to        edge_type timestamp           status_id     
#  <chr>              <chr>     <chr>     <chr>               <chr>         
# 1 761799570426765312 216098950 retweet   2022-02-11 06:14:45 1492019256900~

g <- actor_network %>% Graph() # create igraph object
V(g)$size <- 4
E(g)$arrow.size <- 0.25
V(g)$label <- paste0("@", V(g)$screen_name)
plot(g)
```

Sorry for the confusion, will hopefully be updating CRAN soon.
