### ISSUE TITLE
Having trouble getting hyperlink networks for some sites.

### ISSUE THREAD

**Issue by weiaiwayne** [vosonlab/vosonSML#49]
Error in `dplyr::mutate()`:
! Problem while computing `url = ifelse(...)`.
Caused by error in `stri_replace_first_regex()`:
! Incorrectly nested parentheses in regexp pattern. (U_REGEX_MISMATCHED_PAREN, context=`#:~:text=曉藍 (136)-,本週財經看點 (153),-李進 (404$`)

**Comment by bryn-g** [comment]
Hi @weiaiwayne,

Thank you for posting that error. There appears to be a problem with a URL related regex and grouping that I will investigate. Thanks again for letting me know about this problem, much appreciated.

**Comment by rjackland** [comment]
Hello,
Thanks for reporting this error. It would probably help us if you give the structure of the URL you are trying to crawl. You don't need to report the exact URL, but something like https://xxx.xx/x but please put in any characters that are not a-z e.g. (,}? etc. or whatever. I guess there is a string parsing error.
