### ISSUE TITLE
Collect(<thread.reddit>) suddenly fails with 403 error but RedditExtractoR succeeds

### ISSUE THREAD

**Issue by sbinn** [vosonlab/vosonSML#55]
On R 4.3.2 with vosonSML 0.34.2, it seems that `Collect(<thread.reddit>)` fails with 403 error. However, trying to collect data for the same threads with RedditExtractoR 3.0.9 succeeds. 

Sample:
```
# vosonSML Data Collection --------------------------------------------------
library(vosonSML)
thread_urls <- c(
  "https://www.reddit.com/r/AusFinance/comments/ymkrlr/",
  "https://www.reddit.com/r/AusFinance/comments/ugetai/")
rd_data <- Authenticate("reddit") |>  
  Collect(threadUrls = thread_urls,
          sort = "best", 
          waitTime = c(6, 8),
          writeToFile = TRUE, 
          verbose = TRUE)

# RedditExtractoR Data Collection --------------------------------------------------
library(RedditExtractoR)
rex_data <- get_thread_content(thread_urls)
```
Error message for vosonSML collection:
![reddit-error](https://github.com/vosonlab/vosonSML/assets/48778310/91501249-f0c2-4ca5-be43-1f8711e4f57c)

**Comment by bryn-g** [comment]
Thanks @sbinn. I am encountering the same problem. It may be `vosonSML` or the packages we use to make requests (or particular versions of them) are being blocked for some reason. Using a custom user-agent previously fixed blocking problems but there may be a new issue preventing that from working. Same as Issue #58.

**Comment by sbinn** [comment]
Thank you for picking this up in Issue #58. Thus, I'll close this issue. 

BTW, if you ever need someone to test commits, I'd be happy to contribute.
