### ISSUE TITLE
Failing reddit thread listing and thread collect functions

### ISSUE THREAD

**Issue by bryn-g** [vosonlab/vosonSML#58]
There seems to be recent new issues with the `httr` and `RCurl` packages and `reddit` GET requests.

In package testing all requests are returning `403` error codes indicating the requests are being blocked by the `reddit` server. This is occurring for both default package (`httr`) and custom user-agent strings under the R environment. It may be related to package or environment changes with `R 4.4`.

As blocking is determined by a number of conditions it may not occur for everyone and it may be temporary. It does not appear to be IP related as reddit json could be requested and retrieved using a web browser and `curl` installed on the same test system with default user-agent strings.

This issue was not occurring a few weeks ago under `R 4.3` at the end of April 2024. It now occurs under a fresh `R 4.3` install using the latest package versions, previous package versions have not yet been tested.

**Comment by bryn-g** [comment]
Have updated `reddit` GET requests to use a working base R method and package will be updated shortly.

**Comment by sbinn** [comment]
Thanks for the update! I just tested `vosonSML 0.34.3` on `R 4.3.3`, and `Collect(<thread.reddit>)` succeeded. :)

**Comment by rjackland** [comment]
I have installed vosonSML 0.34.3 in fresh installs of R 4.3.3 on Windows 10 and Ubuntu 22.04, both running in Virtual Box VMs.

The reddit collection is working fine in Ubuntu 22.04 but I'm getting the 403 error in Win10.

Both installs have httr_1.4.7 and curl_5.2.1.

**Comment by bryn-g** [comment]
Apologies for the delay in resolving this issue. The updated package in commit 5fa70dc has implemented a new method and should work across platforms and package versions.
